version: '3.0'

services:
  mongo:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: mongo
    restart: always
    stop_signal: SIGINT
    ports:
      - '27017:27017'
    volumes:
      - ~/mongo/data:/data/db

  auth-service:
    build: ./server-authentication
    container_name: auth-service
    stop_signal: SIGINT
    ports:
      - '5555:5555'

  exp-service:
    build: ./server-experiment
    container_name: exp-service
    stop_signal: SIGINT
    ports:
      - '5050:5050'
    depends_on:
      - auth-service
      - emf-cloud-service

  emf-cloud-service:
    build: ./server-emf-cloud
    container_name: emf-cloud-service
    stop_signal: SIGINT
    ports:
      - '8081:8081'

  web-app:
    build: ./web-app
    container_name: web-app
    stop_signal: SIGINT
    ports:
      - '7001:7001'
    depends_on:
      - auth-service
      - exp-service

  nginx:
    image: nginx:latest
    container_name: nginx-servers
    stop_signal: SIGINT
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - auth-service
      - exp-service
    restart: always

  proxy-service:
    image: ghcr.io/yagorezende/extremexp-abacproxy:dev
    container_name: proxy-service
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - ${FLASK_APP_PORT}:${FLASK_APP_PORT}
    environment:
      - FLASK_APP_HOST=${FLASK_APP_HOST}
      - FLASK_APP_PORT=${FLASK_APP_PORT}
      - FLASK_APP_NAME=${FLASK_APP_NAME}
      - FLASK_APP_DEBUG=${FLASK_APP_DEBUG}
      - FLASK_APP_ENV=${FLASK_APP_ENV}
      - FLASK_APP_SECRET_KEY=${FLASK_APP_SECRET_KEY}
      - FLASK_APP_DATABASE_URI=${FLASK_APP_DATABASE_URI}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - OIDC_OP_AUTHORIZATION_ENDPOINT=${OIDC_OP_AUTHORIZATION_ENDPOINT}
      - OIDC_OP_ENDSESSION_ENDPOINT=${OIDC_OP_ENDSESSION_ENDPOINT}
      - OIDC_OP_JWKS_ENDPOINT=${OIDC_OP_JWKS_ENDPOINT}
      - OIDC_OP_LOGOUT_ENDPOINT=${OIDC_OP_LOGOUT_ENDPOINT}
      - OIDC_OP_LOGOUT_URL_METHOD=${OIDC_OP_LOGOUT_URL_METHOD}
      - OIDC_OP_TOKEN_ENDPOINT=${OIDC_OP_TOKEN_ENDPOINT}
      - OIDC_OP_USER_ENDPOINT=${OIDC_OP_USER_ENDPOINT}
      - OIDC_RP_CLIENT_ID=${OIDC_RP_CLIENT_ID}
      - OIDC_RP_REALM_ID=${OIDC_RP_REALM_ID}
      - OIDC_RP_CLIENT_SECRET=${OIDC_RP_CLIENT_SECRET}
      - OIDC_RP_SIGN_ALGO=${OIDC_RP_SIGN_ALGO}
